// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSG8GZrmxpGH0CjoBAppnxNu5jLbOq36I',
    appId: '1:730330720509:web:bda3dc4bee684b15d57694',
    messagingSenderId: '730330720509',
    projectId: 'twospace-push',
    authDomain: 'twospace-push.firebaseapp.com',
    storageBucket: 'twospace-push.firebasestorage.app',
    measurementId: 'G-HR5DP56Z6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdOToRKC2dfGgRqT8bQcN9TOcTCfgovM',
    appId: '1:730330720509:android:089c73193632da75d57694',
    messagingSenderId: '730330720509',
    projectId: 'twospace-push',
    storageBucket: 'twospace-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcU9RUPWBSsXCwemJROKDT7y41jKwNNk4',
    appId: '1:730330720509:ios:15d6e7ec139a2443d57694',
    messagingSenderId: '730330720509',
    projectId: 'twospace-push',
    storageBucket: 'twospace-push.firebasestorage.app',
    iosBundleId: 'com.example.twoSpaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcU9RUPWBSsXCwemJROKDT7y41jKwNNk4',
    appId: '1:730330720509:ios:15d6e7ec139a2443d57694',
    messagingSenderId: '730330720509',
    projectId: 'twospace-push',
    storageBucket: 'twospace-push.firebasestorage.app',
    iosBundleId: 'com.example.twoSpaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSG8GZrmxpGH0CjoBAppnxNu5jLbOq36I',
    appId: '1:730330720509:web:b73732a78fa86a63d57694',
    messagingSenderId: '730330720509',
    projectId: 'twospace-push',
    authDomain: 'twospace-push.firebaseapp.com',
    storageBucket: 'twospace-push.firebasestorage.app',
    measurementId: 'G-C2BHSYS2VY',
  );
}
